### ISSUE TITLE
Созданные категории видны всем

### ISSUE THREAD

**Issue by Gaikanomer9** [alpha-coders-team/todo-app#50]
Сейчас любая новая категория становится доступна для всех пользователей.
Необходимо сделать привязку по созданным категориям для пользователя, их создавшего

**Comment by vavsar** [comment]
Это должен автор исправить или любой желающий?

**Comment by myagkova** [comment]
Проблема была решена через get_form, но код был удален в https://github.com/alpha-coders-team/todo-app/pull/49/files

**Comment by Gaikanomer9** [comment]
Спасибо @myagkova 👍
